#Database: PostgreSQL (Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Prod global variables
app.frontend-base-url=https://pulse-polling.vercel.app
app.public-base-url-prod=https://pulse-polling.onrender.com
app.share-image-url=https://pulse-polling.vercel.app/pulse-share-card.png
app.public-base-url=https://pulse-polling.vercel.app