spring.application.name=survey-api

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.example.ser421lab6=DEBUG

# Debugging
server.error.include-message=always
server.error.include-binding-errors=always

