#Database: PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/surveyDB
spring.datasource.username=surveyUser
spring.datasource.password=surveyPassword

#Dev global variables
app.frontend-base-url=http://localhost:5173
app.public-base-url-prod=http://localhost:8080
app.share-image-url=http://localhost:5173/pulse-share-card.png
app.public-base-url=http://localhost:5173